export interface CaptionStylePreset {
  id: string;
  name: string;
  textStyle: React.CSSProperties;
  containerStyle?: React.CSSProperties;
}

export const captionPresets: CaptionStylePreset[] = [
  {
    id: "classic-white",
    name: "Classic White",
    textStyle: {
      fontSize: "48px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "white",
      textShadow: "3px 3px 6px rgba(0,0,0,0.9), -1px -1px 2px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
    },
  },
  {
    id: "yellow-highlight",
    name: "Yellow Highlight",
    textStyle: {
      fontSize: "46px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "black",
      backgroundColor: "#FFE135",
      padding: "8px 16px",
      borderRadius: "8px",
      textAlign: "center",
      lineHeight: 1.3,
      margin: 0,
      display: "inline-block",
      width: "fit-content",
    },
  },
  {
    id: "neon-green",
    name: "Neon Green",
    textStyle: {
      fontSize: "50px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#39FF14",
      textShadow:
        "0 0 10px #39FF14, 0 0 20px #39FF14, 0 0 30px #39FF14, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.1,
      textTransform: "uppercase",
      letterSpacing: "2px",
      margin: 0,
      display: "inline-block",
    },
  },
  {
    id: "purple-box",
    name: "Purple Box",
    textStyle: {
      fontSize: "44px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "white",
      backgroundColor: "#8B5CF6",
      padding: "12px 20px",
      borderRadius: "12px",
      textAlign: "center",
      lineHeight: 1.2,
      boxShadow: "0 4px 15px rgba(139, 92, 246, 0.4)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
    },
  },
  {
    id: "retro-yellow",
    name: "Retro Yellow",
    textStyle: {
      fontSize: "48px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "black",
      backgroundColor: "#FFD700",
      padding: "10px 18px",
      borderRadius: "25px",
      textAlign: "center",
      lineHeight: 1.2,
      border: "3px solid black",
      textTransform: "lowercase",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
    },
  },
  {
    id: "blue-modern",
    name: "Blue Modern",
    textStyle: {
      fontSize: "46px",
      fontWeight: "700",
      fontFamily: "Helvetica, Arial, sans-serif",
      color: "#3B82F6",
      backgroundColor: "rgba(0, 0, 0, 0.85)",
      padding: "14px 24px",
      borderRadius: "16px",
      textAlign: "center",
      lineHeight: 1.3,
      backdropFilter: "blur(10px)",
      border: "1px solid rgba(59, 130, 246, 0.3)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
    },
  },
  {
    id: "gradient-fire",
    name: "Gradient Fire",
    textStyle: {
      fontSize: "52px",
      fontWeight: "900",
      fontFamily: "Arial Black, sans-serif",
      background: "linear-gradient(45deg, #FF6B35, #F7931E, #FFD23F)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
      textTransform: "uppercase",
    },
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    textStyle: {
      fontSize: "48px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      color: "#FF1493",
      textShadow:
        "0 0 5px #FF1493, 0 0 10px #FF1493, 0 0 15px #FF1493, 0 0 20px #FF1493, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
      letterSpacing: "1px",
    },
  },
  {
    id: "outlined-bold",
    name: "Outlined Bold",
    textStyle: {
      fontSize: "50px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "white",
      textShadow:
        "-3px -3px 0 #000, 3px -3px 0 #000, -3px 3px 0 #000, 3px 3px 0 #000, 0 0 15px rgba(255,255,255,0.5)",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
  {
    id: "glass-effect",
    name: "Glass Effect",
    textStyle: {
      fontSize: "44px",
      fontWeight: "600",
      fontFamily: "Helvetica, Arial, sans-serif",
      color: "rgba(255, 255, 255, 0.9)",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      padding: "16px 24px",
      borderRadius: "20px",
      textAlign: "center",
      lineHeight: 1.3,
      backdropFilter: "blur(20px)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.3)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    textStyle: {
      fontSize: "46px",
      fontWeight: "bold",
      fontFamily: "Courier New, monospace",
      color: "#00FFFF",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: "12px 20px",
      borderRadius: "4px",
      textAlign: "center",
      lineHeight: 1.2,
      border: "2px solid #00FFFF",
      boxShadow:
        "0 0 20px rgba(0, 255, 255, 0.5), inset 0 0 20px rgba(0, 255, 255, 0.1)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      textTransform: "uppercase",
      letterSpacing: "2px",
    },
  },
  {
    id: "gradient-sunset",
    name: "Gradient Sunset",
    textStyle: {
      fontSize: "48px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
    },
  },
  {
    id: "comic-book",
    name: "Comic Book",
    textStyle: {
      fontSize: "48px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#FFD700",
      backgroundColor: "#FF4444",
      padding: "12px 20px",
      borderRadius: "8px",
      textAlign: "center",
      lineHeight: 1.1,
      border: "4px solid #000",
      textShadow: "2px 2px 0 #000",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      textTransform: "uppercase",
      letterSpacing: "1px",
    },
  },
  {
    id: "holographic",
    name: "Holographic",
    textStyle: {
      fontSize: "50px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      background:
        "linear-gradient(45deg, #ff0080, #ff8c00, #40e0d0, #ff0080, #ff8c00)",
      backgroundSize: "300% 300%",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(0 0 10px rgba(255, 255, 255, 0.5))",
      animation: "holographic 3s ease-in-out infinite",
    },
  },
  {
    id: "retro-80s",
    name: "Retro 80s",
    textStyle: {
      fontSize: "48px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "#FF00FF",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: "14px 22px",
      borderRadius: "0",
      textAlign: "center",
      lineHeight: 1.2,
      border: "3px solid #00FFFF",
      textShadow: "3px 3px 0 #FF00FF, 6px 6px 0 #00FFFF",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      textTransform: "uppercase",
      letterSpacing: "2px",
    },
  },
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    textStyle: {
      fontSize: "44px",
      fontWeight: "300",
      fontFamily: "Helvetica Neue, Arial, sans-serif",
      color: "white",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      padding: "16px 28px",
      borderRadius: "30px",
      textAlign: "center",
      lineHeight: 1.4,
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      letterSpacing: "0.5px",
    },
  },
  {
    id: "graffiti-style",
    name: "Graffiti Style",
    textStyle: {
      fontSize: "52px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#FFFFFF",
      textShadow:
        "3px 3px 0 #FF6B35, 6px 6px 0 #F7931E, 9px 9px 0 #FFD23F, 12px 12px 20px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
      letterSpacing: "2px",
      transform: "rotate(-2deg)",
    },
  },
  {
    id: "neon-blue",
    name: "Neon Blue",
    textStyle: {
      fontSize: "48px",
      fontWeight: "700",
      fontFamily: "Arial, sans-serif",
      color: "#00BFFF",
      textShadow:
        "0 0 5px #00BFFF, 0 0 10px #00BFFF, 0 0 15px #00BFFF, 0 0 20px #00BFFF, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
      letterSpacing: "1px",
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    textStyle: {
      fontSize: "46px",
      fontWeight: "bold",
      fontFamily: "Georgia, serif",
      background: "linear-gradient(45deg, #FFD700, #FFA500, #FFD700)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.3,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
      textShadow: "none",
    },
  },
  {
    id: "bubble-pop",
    name: "Bubble Pop",
    textStyle: {
      fontSize: "46px",
      fontWeight: "800",
      fontFamily: "Arial Rounded MT Bold, Arial, sans-serif",
      color: "#FF69B4",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      padding: "14px 24px",
      borderRadius: "50px",
      textAlign: "center",
      lineHeight: 1.2,
      border: "4px solid #FF69B4",
      boxShadow: "0 6px 20px rgba(255, 105, 180, 0.4)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      textTransform: "lowercase",
    },
  },
  {
    id: "matrix-green",
    name: "Matrix Green",
    textStyle: {
      fontSize: "44px",
      fontWeight: "bold",
      fontFamily: "Courier New, monospace",
      color: "#00FF41",
      backgroundColor: "rgba(0, 0, 0, 0.9)",
      padding: "12px 20px",
      borderRadius: "4px",
      textAlign: "center",
      lineHeight: 1.2,
      textShadow: "0 0 10px #00FF41",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      letterSpacing: "1px",
    },
  },
  {
    id: "rainbow-gradient",
    name: "Rainbow Gradient",
    textStyle: {
      fontSize: "50px",
      fontWeight: "900",
      fontFamily: "Arial Black, sans-serif",
      background:
        "linear-gradient(45deg, #ff0000, #ff8000, #ffff00, #80ff00, #00ff00, #00ff80, #00ffff, #0080ff, #0000ff, #8000ff, #ff00ff, #ff0080)",
      backgroundSize: "300% 300%",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
      textTransform: "uppercase",
    },
  },
  {
    id: "vintage-film",
    name: "Vintage Film",
    textStyle: {
      fontSize: "48px",
      fontWeight: "bold",
      fontFamily: "Times New Roman, serif",
      color: "#F5E6D3",
      backgroundColor: "rgba(139, 69, 19, 0.8)",
      padding: "16px 24px",
      borderRadius: "8px",
      textAlign: "center",
      lineHeight: 1.3,
      border: "2px solid #8B4513",
      textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
      margin: 0,
      display: "inline-block",
      width: "fit-content",
      letterSpacing: "1px",
    },
  },
  {
    id: "electric-purple",
    name: "Electric Purple",
    textStyle: {
      fontSize: "48px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      color: "#9D4EDD",
      textShadow:
        "0 0 5px #9D4EDD, 0 0 10px #9D4EDD, 0 0 15px #9D4EDD, 0 0 20px #9D4EDD, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
      letterSpacing: "2px",
    },
  },
];
