export interface CaptionStylePreset {
  id: string;
  name: string;
  textStyle: React.CSSProperties;
  containerStyle?: React.CSSProperties;
}

export const captionPresets: CaptionStylePreset[] = [
  {
    id: "classic-white",
    name: "Classic White",
    textStyle: {
      fontSize: "24px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "white",
      textShadow: "3px 3px 6px rgba(0,0,0,0.9), -1px -1px 2px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
    },
  },
  {
    id: "neon-green",
    name: "Neon Green",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#39FF14",
      textShadow:
        "0 0 10px #39FF14, 0 0 20px #39FF14, 0 0 30px #39FF14, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.1,
      textTransform: "uppercase",
      margin: 0,
      display: "inline-block",
    },
  },
  {
    id: "gradient-fire",
    name: "Gradient Fire",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Arial Black, sans-serif",
      background: "linear-gradient(45deg, #FF6B35, #F7931E, #FFD23F)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
      textTransform: "uppercase",
    },
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    textStyle: {
      fontSize: "24px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      color: "#FF1493",
      textShadow:
        "0 0 5px #FF1493, 0 0 10px #FF1493, 0 0 15px #FF1493, 0 0 20px #FF1493, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
  {
    id: "outlined-bold",
    name: "Outlined Bold",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "white",
      textShadow:
        "-3px -3px 0 #000, 3px -3px 0 #000, -3px 3px 0 #000, 3px 3px 0 #000, 0 0 15px rgba(255,255,255,0.5)",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
  {
    id: "gradient-sunset",
    name: "Gradient Sunset",
    textStyle: {
      fontSize: "24px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
    },
  },
  {
    id: "comic-book",
    name: "Comic Book",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#FFD700",
      backgroundColor: "#FF4444",
      borderRadius: "8px",
      textAlign: "center",
      lineHeight: 1.1,
      border: "4px solid #000",
      textShadow: "2px 2px 0 #000",
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
  {
    id: "holographic",
    name: "Holographic",
    textStyle: {
      fontSize: "24px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      background:
        "linear-gradient(45deg, #ff0080, #ff8c00, #40e0d0, #ff0080, #ff8c00)",
      backgroundSize: "300% 300%",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(0 0 10px rgba(255, 255, 255, 0.5))",
      animation: "holographic 3s ease-in-out infinite",
    },
  },
  {
    id: "retro-80s",
    name: "Retro 80s",
    textStyle: {
      fontSize: "24px",
      fontWeight: "bold",
      fontFamily: "Arial, sans-serif",
      color: "#FF00FF",
      // padding: "14px 22px",
      borderRadius: "0",
      textAlign: "center",
      lineHeight: 1.2,
      // border: "3px solid #00FFFF",
      textShadow: "3px 3px 0 #FF00FF, 6px 6px 0 #00FFFF",
      margin: 0,
      display: "inline-block",
      // width: "fit-content",
      textTransform: "uppercase",
    },
  },
  {
    id: "graffiti-style",
    name: "Graffiti Style",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Impact, Arial Black, sans-serif",
      color: "#FFFFFF",
      textShadow:
        "3px 3px 0 #FF6B35, 6px 6px 0 #F7931E, 9px 9px 0 #FFD23F, 12px 12px 20px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
      transform: "rotate(-2deg)",
    },
  },
  {
    id: "neon-blue",
    name: "Neon Blue",
    textStyle: {
      fontSize: "24px",
      fontWeight: "700",
      fontFamily: "Arial, sans-serif",
      color: "#00BFFF",
      textShadow:
        "0 0 5px #00BFFF, 0 0 10px #00BFFF, 0 0 15px #00BFFF, 0 0 20px #00BFFF, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
  {
    id: "rainbow-gradient",
    name: "Rainbow Gradient",
    textStyle: {
      fontSize: "24px",
      fontWeight: "900",
      fontFamily: "Arial Black, sans-serif",
      background:
        "linear-gradient(45deg, #ff0000, #ff8000, #ffff00, #80ff00, #00ff00, #00ff80, #00ffff, #0080ff, #0000ff, #8000ff, #ff00ff, #ff0080)",
      backgroundSize: "300% 300%",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      textAlign: "center",
      lineHeight: 1.1,
      margin: 0,
      display: "inline-block",
      filter: "drop-shadow(2px 2px 4px rgba(0,0,0,0.8))",
      textTransform: "uppercase",
    },
  },

  {
    id: "electric-purple",
    name: "Electric Purple",
    textStyle: {
      fontSize: "24px",
      fontWeight: "800",
      fontFamily: "Arial, sans-serif",
      color: "#9D4EDD",
      textShadow:
        "0 0 5px #9D4EDD, 0 0 10px #9D4EDD, 0 0 15px #9D4EDD, 0 0 20px #9D4EDD, 2px 2px 4px rgba(0,0,0,0.8)",
      textAlign: "center",
      lineHeight: 1.2,
      margin: 0,
      display: "inline-block",
      textTransform: "uppercase",
    },
  },
];
